### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by kassane** [tw4452852/barn#1]
Hi @tw4452852 

Cool the project! I'm also testing the `cpu` being ported rust.

But I wanted to know if you intend to add SSH support as well as in the original application?

**Comment by tw4452852** [comment]
Hi @kassane 

Yes, this is on my TODO list.

**Comment by kassane** [comment]
I am planning to bring up a possible implementation using libssh2.
However, I will try to learn how it works since I have only used libs written in Go.
https://github.com/mattnite/zig-libssh2
